#!/usr/bin/python3
"""Test parameters for creating and querying objects"""

from models.state import State
from models.place import Place
from models import storage

if __name__ == "__main__":
    # Create States
    states_to_create = ["California", "Arizona"]
    for state_name in states_to_create:
        new_state = State(name=state_name)
        new_state.save()

    # Query all States
    all_states = storage.all(State)
    print("All States:")
    for state in all_states.values():
        print(state)

    # Create a Place
    new_place_data = {
        "city_id": "0001",
        "user_id": "0001",
        "name": "My_little_house",
        "number_rooms": 4,
        "number_bathrooms": 2,
        "max_guest": 10,
        "price_by_night": 300,
        "latitude": 37.773972,
        "longitude": -122.431297
    }
    new_place = Place(**new_place_data)
    new_place.save()

    # Query all Places
    all_places = storage.all(Place)
    print("All Places:")
    for place in all_places.values():
        print(place)
